language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry phpenv rehash

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src test
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - php php-coveralls.phar
