language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src test
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=psr2 -sp src

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar
